[build]
  publish = "dist"
  command = "bun run build"

# Omdirigera alla /api/-anrop direkt till din Render-backend
[[redirects]]
  from = "/api/*"
  to = "https://dela-su0g.onrender.com/api/:splat"
  status = 200
  force = true

# Hantera Single Page Application (PWA) rutter på Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
